### ISSUE TITLE
Cartfile build error

### ISSUE THREAD

**Issue by hellohelloye** [dekatotoro/SlideMenuControllerSwift#138]
```
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Fetching SlideMenuControllerSwift
*** Checking out SlideMenuControllerSwift at "2.1.0"
*** Checking out SwiftyJSON at "2.3.3"
*** Checking out Alamofire at "2.0.0"
*** xcodebuild output can be found in /var/folders/44/v8qg_df974bfxmpc33nm0tb00000gn/T/carthage-xcodebuild.aBSU1v.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "SlideMenuControllerSwift-iOS" in SlideMenuControllerSwift.xcodeproj


** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:245:79: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:245:79: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:245:79: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:245:79: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:251:79: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:251:79: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:251:79: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:251:79: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:262:80: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:262:80: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:262:80: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:262:80: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:268:80: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:268:80: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:268:80: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:268:80: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:995:136: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:995:136: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:995:136: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:995:136: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:1000:137: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:1000:137: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:1000:137: error: expected expression in list of expressions
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:1000:137: error: expected ',' separator
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:245:56: error: missing argument for parameter 'action' in call
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:251:56: error: missing argument for parameter 'action' in call
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:262:57: error: missing argument for parameter 'action' in call
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:268:57: error: missing argument for parameter 'action' in call
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:995:43: error: cannot invoke initializer for type 'UIBarButtonItem' with an argument list of type '(image: UIImage, style: UIBarButtonItemStyle, target: UIViewController)'
/Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift:1000:44: error: cannot invoke initializer for type 'UIBarButtonItem' with an argument list of type '(image: UIImage, style: UIBarButtonItemStyle, target: UIViewController)'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/***/Desktop/***/Carthage/Checkouts/SlideMenuControllerSwift/Source/SlideMenuController.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

**Comment by Pluto-Y** [comment]
@hellohelloye 
Have you update Xcode?
It seems it's the syntax error of Swift 3.0.

**Comment by goldenlimit** [comment]
@hellohelloye if you using old Xcode, 
Just use this syntax style:
`Selector("GpsViewController.changeMode")`
rather than `#selector(GpsViewController.changeMode)`

**Comment by Codeido** [comment]
Hi @hellohelloye   
The actual version works great with Swift 2.3 and Swift 3. Try this new release.
More info: https://github.com/dekatotoro/SlideMenuControllerSwift/commit/a74a0a26c21a49dcd4ed0c24fb352a68f89eff33

Thanks
- Paolo

**Comment by kevinmlong** [comment]
I can't get it to build with either 3.0.0 or master. It fails on:

```
A shell task (/usr/bin/xcrun xcodebuild -project "/Users/klong/PATH_TO_PROJECT/Carthage/Checkouts/SlideMenuControllerSwift/SlideMenuControllerSwift.xcodeproj" -scheme SlideMenuControllerSwift-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
```

**Comment by bitomule** [comment]
I tried github `"dekatotoro/SlideMenuControllerSwift" "master"` and worked. I think project just needs a new tag with last version.
